version: "3.8"

volumes:
  pg_data:

services:
  # https://hub.docker.com/_/postgres
  postgres:
    image: mirror.gcr.io/postgres:15-alpine
    environment:
      POSTGRES_USER: "assets"
      POSTGRES_PASSWORD: "assets"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  assets:
    build:
      context: ./
      dockerfile: ./Dockerfile_development
    environment:
      PORT: "3000"
      ADDR: "0.0.0.0"
      DB_URL: "user=assets password=assets dbname=assets host=postgres port=5432 sslmode=disable"
    ports:
      - "3000:3000"
